package com.makaia.MakaiaProyectoFinal.enums;

public enum EstadoAspirante {
    PROCESO_DE_PRUEBA,
    NO_ADMITIDO_BECA,
    REMITIDO_ENTREVISTA_BECA,
    DOCUMENTACION,
    ADMITIDO_BECA,
    DESCARTADO_BECA,
    DESCARTADO_COMERCIAL,
    EN_PROCESO_COMERCIAL,
    REMITIDO_ENTREVISTA_COMERCIAL,
    ADMITIDO_COMERCIAL,
    DESISTIO
}
