package com.makaia.MakaiaProyectoFinal.enums;

public enum TipoDocumento {
    CEDULA_DE_CIUDADANIA_COLOMBIANA,
    TARJETA_DE_IDENTIDAD_COLOMBIANA,
    CEDULA_DE_IDENTIDAD_VENEZOLANA,
    PPT_PERMISO_POR_PROTECCION_TEMPORAL,
    PEP_PERMISO_ESPECIAL_DE_PERMANENCIA,
    CEDULA_DE_EXTRANJERIA

}
